language: crystal
services:
  - docker
script:
  - docker run --name tarantool -d -p 3301:3301 tarantool/tarantool:1
  - crystal spec
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
